### ISSUE TITLE
Arquitectura de Proyecto

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/actividad-10-practica-de-arquitectura-equipo-jad#1]
https://github.com/SistemasTecTlaxiaco/Money-Digital/wiki/Arquitectura-de-Software-para-Web-3.0

Reporte de la práctica 10

[Reporte de practica 10.pdf](https://github.com/user-attachments/files/18042732/Reporte.de.practica.10.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
De acuerdo a la rúbrica obtuviste 28%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
