### ISSUE TITLE
diagrama de componentes

### ISSUE THREAD

**Issue by Kevinosorio77** [SistemasTecTlaxiaco/actividad-10-practica-de-arquitectura-equipo-jad#2]
[Diagrama_de_componentes[2].pdf](https://github.com/user-attachments/files/18043604/Diagrama_de_componentes.2.pdf)

**Comment by IrvinSanchez-dev** [comment]
**Comentario*** Este no es el documento de diagrama de componentes, por favor corregir

**Comment by IrvinSanchez-dev** [comment]
Dado la rúbrica de evaluación obtuvieron un 28% de 30%

**No tienen nombre las imágenes, y tiene solo 10 líneas en la conclusión.**

**Comment by josealfredo79** [comment]
Revisado...
